# Looks at contributors to annual consumption
# Gets package size purchase differences between rich and poor households after
# controlling for household characteristics.
library(data.table)
library(lfe)
library(stargazer)
library(glmnet)
library(doMC)
library(ggplot2)
library(ggthemes)
library(purrr)
library(stringr)
registerDoMC(cores = 4)
threads <- 8
yrs <- 2004:2017
path <- "/scratch/upenn/hossaine/"

# Loading product data
prod <- fread(paste0(path, "fullProd.csv"), nThread = threads,
              select = c("upc", "upc_ver_uc", "totalAmount"))

# Loading trips data
trips <- fread(paste0(path, "fullTrips.csv"), nThread = threads,
               select = c("trip_code_uc", "household_code", "panel_year",
                          "purchase_date"))

# Loading panel data
panel <- fread(paste0(path, "fullPanel.csv"), nThread = threads)

# Getting purchase data by household year
fullPurch <- NULL
for (i in yrs) {
  print(i)
  purch <- fread(paste0(path, "fullPurch", i, ".csv"), nThread = threads,
                 select = c("trip_code_uc", "upc", "upc_ver_uc", "quantity",
                            "product_module_code", "food"))
  fullPurch <- rbindlist(list(fullPurch, purch), use.names = TRUE)
}

# Combining all purchases together
fullPurch <- merge(fullPurch, prod, by = c("upc", "upc_ver_uc"))
fullPurch[, "Q" := quantity * totalAmount]
fullPurch[, c("totalAmount", "quantity", "upc", "upc_ver_uc") := NULL]

# Merging in trips
fullPurch <- merge(fullPurch, trips, by = "trip_code_uc")[, "trip_code_uc" := NULL]
fullPurch[, "purchase_date" := as.Date(as.character(purchase_date))]
setorder(fullPurch, household_code, panel_year, product_module_code, purchase_date)
rm(trips, prod, purch)

# Getting first and last purchase dates and final purchase amount
finalDatePurch <- fullPurch[, .(start_date = head(purchase_date, 1),
                                end_date = tail(purchase_date, 1),
                                final = tail(Q, 1)),
                            by = .(household_code, panel_year,
                                   product_module_code, food)]
finalDatePurch[, "days" := as.integer(end_date - start_date)]
finalDatePurch[, c("start_date", "end_date") := NULL]

# Getting annual purchases and removing final purchase from tally
annualPurch <- fullPurch[, .(fullQ = sum(Q, na.rm = TRUE)),
                         by = .(household_code, panel_year,
                                product_module_code, food)]
annualPurch <- merge(annualPurch, finalDatePurch,
                     by = c("household_code", "panel_year",
                            "product_module_code", "food"))
annualPurch[, "consRate" := (fullQ - final) / days]
annualPurch[, c("fullQ", "final", "days") := NULL]
annualPurch[is.nan(consRate), "consRate" := NA]
rm(finalDatePurch, fullPurch)

# Merging with panel data to do predictive regression
# Removing any undefined consumption generated by only a single purchase in a year
# and removing any outliers above the top 1% or below the bottom 1% of purchases
annualPurch <- merge(annualPurch, panel, by = c("household_code", "panel_year"))
annualPurch[, "household_income" := as.factor(household_income)]
annualPurch <- annualPurch[consRate > 0 & consRate < Inf]
annualPurch[, "top1" := quantile(consRate, 0.99), by = .(product_module_code, food)]
annualPurch[, "bottom1" := quantile(consRate, 0.01), by = .(product_module_code, food)]
annualPurch <- annualPurch[consRate < top1 & consRate > bottom1]
fwrite(annualPurch, "/scratch/upenn/hossaine/annualPurchAllMods.csv", nThread = threads)

########################## REGRESSION ##########################################
#annualPurch <- fread("/scratch/upenn/hossaine/annualPurchAllMods.csv", nThread = threads)
annualPurch[, "household_income_cts" :=
              factor(household_income,
                     levels = c(3, 4, 6, 8, 10, 11, 13, 15, 16, 17, 18, 19, 21,
                                23, 26, 27),
                     labels = c(2.5, 6.5, 9, 11, 13.5, 17.5, 22.5, 27.5, 32.5,
                                37.5, 42.5, 47.5, 55, 65, 85, 100),
                     ordered = TRUE)]
annualPurch[, "household_income_cts" := as.numeric(as.character(household_income_cts))]
annualPurch[, "lInc" := log(household_income_cts)]
annualPurch[, "lRate" := log(consRate)]

# Getting non-food modules
mods <- unique(annualPurch[food == 0]$product_module_code)

# Get consumption coefficient
getCons <- function(modCode) {
  regData <- annualPurch[product_module_code == modCode]
  tryCatch({
    reg <- felm(lRate ~ household_income_coarse + household_size + age + married + child |
                  dma_cd + panel_year, data = regData,
                weights = regData$projection_factor)
    regCoef <- as.data.table(summary(reg)$coefficients,
                             keep.rownames = TRUE)[grepl("household_income*", rn)]
    regCoef[, "mod" := modCode]
    regCoef[, "food" := unique(regData$food)]
    return(regCoef)
  }, error = function(e){})
}

finalCoefs <- rbindlist(map(mods, getCons), use.names = TRUE)

# Organizing graph data
finalCoefs[, "rn" := gsub("household_income_coarse", "", rn)]
setnames(finalCoefs, c("rn", "beta", "se", "t", "p", "mod", "food"))
finalCoefs[, "sigEst" := ifelse(p < 0.05, beta, 0)]
setorder(finalCoefs, rn, -sigEst)
finalCoefs[, "rn" := factor(rn, levels = c("25-50k", "50-100k", ">100k"),
                            ordered = TRUE)]

# Graphing Data
ggplot(data = finalCoefs, aes(x = sigEst)) +
  geom_histogram(bins = 50, aes(y = ..density..)) +
  geom_hline(yintercept = 0) +
  facet_wrap(vars(rn)) +
  labs(title = "Consumption Is Similar For Non-Food Products",
       x = "Difference in Log Annual Consumption", y = "Density",
       caption = str_wrap(paste0("Source: Author calulations from Nielsen ",
                                 "Consumer Panel. Note: Figure plots the ",
                                 "distribution of differences in log annual ",
                                 "consumption for ",
                                 "each income quartile relative to households ",
                                 "making under $25k. Each coefficient is for a ",
                                 "different non-food product category. Regression ",
                                 "controls for household size, age, marital ",
                                 "status, and presence of children."))) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(), plot.caption = element_text(hjust = 0)) +
  scale_color_grey()

ggsave(filename = "./figures/annualPurchasesAllMods.png", height = 6, width = 6)
